In [23]:
import numpy as np
import pandas as pd

Merging 2 dataframe

In [63]:
employees = pd.DataFrame({
    "employee_id":[1,2,3,4,5],
    "name":["john","Anna","Peter","linda","bob"],
    "department":["HR","IT","Finance","IT","HR"]
})
# DATAFRAME 2 : SALARY information
salaries = pd.DataFrame({
    "employee_id":[1,2,3,6,7],
    "salary":[60000,85000,80000,70000,90000],
    "Bonus":[5000,10000,7000,12000,8000]
})

In [64]:
employees

   employee_id   name department
0            1   john         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  linda         IT
4            5    bob         HR

In [56]:
salaries

   employee_id  salary  Bonus
0            1   60000   5000
1            2   85000  10000
2            3   80000   7000
3            6   70000  12000
4            7   90000   8000

In [ ]:
# there are two variations we can concatinate these two data frame

In [71]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  Bonus
0            1   john         HR   60000   5000
1            2   Anna         IT   85000  10000
2            3  Peter    Finance   80000   7000

In [70]:
pd.merge(employees,salaries,on="employee_id",how="outer") # outer merge both the data frame and display empty valuues as NAN

   employee_id   name department   salary    Bonus
0            1   john         HR  60000.0   5000.0
1            2   Anna         IT  85000.0  10000.0
2            3  Peter    Finance  80000.0   7000.0
3            4  linda         IT      NaN      NaN
4            5    bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  12000.0
6            7    NaN        NaN  90000.0   8000.0

In [73]:
pd.merge(employees,salaries,on="employee_id",how="left") # lefts means i merge the data on the basis of employes

   employee_id   name department   salary    Bonus
0            1   john         HR  60000.0   5000.0
1            2   Anna         IT  85000.0  10000.0
2            3  Peter    Finance  80000.0   7000.0
3            4  linda         IT      NaN      NaN
4            5    bob         HR      NaN      NaN

In [74]:
pd.merge(employees,salaries,on="employee_id",how="right")

   employee_id   name department  salary  Bonus
0            1   john         HR   60000   5000
1            2   Anna         IT   85000  10000
2            3  Peter    Finance   80000   7000
3            6    NaN        NaN   70000  12000
4            7    NaN        NaN   90000   8000

CONCATINATION OF 2 DataFrame

In [76]:
 df1=pd.DataFrame({
     "A":["A0","A1","A2"],
     "B":["B0","B1","B2"],
     "C":["C1","C2","C3"]
 })                                   # LIST {}
 df2=pd.DataFrame({
     "A":["A3","A4","A5"],
     "B":["B3","B4","B5"],
     "C":["C3","C4","C5"]
 })

In [77]:
df1

    A   B   C
0  A0  B0  C1
1  A1  B1  C2
2  A2  B2  C3

In [78]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#  Concatination functions (concat)

In [80]:
pd.concat([df1,df2]) # CONCATE BOTH THE DATA FRAME

    A   B   C
0  A0  B0  C1
1  A1  B1  C2
2  A2  B2  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [85]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C1  A3  B3  C3
1  A1  B1  C2  A4  B4  C4
2  A2  B2  C3  A5  B5  C5

**joining 2 Dataframes

In [97]:
df1=pd.DataFrame({
    "name":["Abhay","Akshit","charlie"]
},index = [1,2,3])
# second dataFrame 
df2=pd.DataFrame({
    "score":[85,90,75]
},index=[1,2,3])

In [93]:
df1

      name
1    Abhay
2   Akshit
3  charlie

In [91]:
df2

   score
2     85
3     90
4     75

In [94]:
# i want to joint df1 +df2

In [99]:
df1.join(df2,how="outer")

      name  score
1    Abhay     85
2   Akshit     90
3  charlie     75

In [100]:
df2.join(df1)

   score     name
1     85    Abhay
2     90   Akshit
3     75  charlie