MISSING DATA

In [2]:
import numpy as np 
import pandas as pd

Finding Missing Data

In [4]:
data={
    "A":[1,2,np.nan,4,5],
    "B":[1,2,3,4,5],
    "C":[1,2,3,np.nan,np.nan],
    "d":[1,np.nan,np.nan,np.nan,5]
    
}
cf=pd.DataFrame(data)

In [5]:
cf.isna() # is use to find the missing data which return the missing values in True.

       A      B      C      d
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
cf.isna().sum()

A    1
B    0
C    2
d    3
dtype: int64

In [7]:
cf.isna().any()  # any is use to find the null values in pandas

A     True
B    False
C     True
d     True
dtype: bool

Removing the Null values in the Missing Data

In [8]:
cf

     A  B    C    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
cf.dropna(thresh=3)  # thresh is used to remove all the null  values

     A  B    C    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Fill the missing values

In [10]:
cf.fillna(0)

     A  B    C    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [11]:
values = {'A' : 0 , 'B' : 100 , 'C' : 300 , 'D' : 400}
cf.fillna(value=values) #fillna is used to fill the null value

     A  B      C    d
0  1.0  1    1.0  1.0
1  2.0  2    2.0  NaN
2  0.0  3    3.0  NaN
3  4.0  4  300.0  NaN
4  5.0  5  300.0  5.0

In [12]:
cf

     A  B    C    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
cf.fillna(cf.mean())

     A  B    C    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0