# Pandas series

In [3]:
import numpy as np 
import pandas as pd

In [4]:
lables=["a","b","c"]
my_list=[10,20,30]
my_arr=np.array([10,20,30])
d={1:0,2:20,3:30}

In [5]:
pd.Series(my_list,index=lables)

a    10
b    20
c    30
dtype: int64

# we can set the custom lables

In [6]:
pd.Series(my_arr,index=d) # index is the lables like a boolet point in the presentation

1    10
2    20
3    30
dtype: int64

# DATAfRAMES

creating a DataFrame

# By using the dictionary

In [7]:
data={
    "Name": ["john","Anna","Linda","peter"],
    "Age": [12,14,16,18],
    "city": ["california","us","japan","china"],
    "salary": [10000,20000,30000,40000]
}
df=pd.DataFrame(data)
df

    Name  Age        city  salary
0   john   12  california   10000
1   Anna   14          us   20000
2  Linda   16       japan   30000
3  peter   18       china   40000

# BY using list

In [8]:
data_list = [
    ["jon",28,"newyork",200000],
    ["Anna",20,"paris",30000],
    ["peter",40,"bariline",20000], 
    ["linda",30,"India",20000]
]
df2=pd.DataFrame(data_list)

In [9]:
df2

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [10]:
columns=["Name"	,"Age","city","salary"]
pd.DataFrame(data_list,columns=columns)

    Name  Age      city  salary
0    jon   28   newyork  200000
1   Anna   20     paris   30000
2  peter   40  bariline   20000
3  linda   30     India   20000

Selection and indexing and column

In [11]:

df2

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [12]:
df2[[0,1,2,3]]

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [13]:
#create a new column

In [14]:
df2["designation"]=["doctor","engineer","doctore","engineer"]

In [15]:
df2

       0   1         2       3 designation
0    jon  28   newyork  200000      doctor
1   Anna  20     paris   30000    engineer
2  peter  40  bariline   20000     doctore
3  linda  30     India   20000    engineer

Removing a column

In [16]:
df2.drop('designation',axis=1)

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [17]:
df2.drop('designation',axis=1,inplace=True)

In [18]:
df2

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [19]:
 # now we are going to selecting a row in the DataFrame

In [20]:
df2

       0   1         2       3
0    jon  28   newyork  200000
1   Anna  20     paris   30000
2  peter  40  bariline   20000
3  linda  30     India   20000

In [21]:
df2.loc[[0,3,2,1]] # for selecting the row in the data fram by ysing loc

       0   1         2       3
0    jon  28   newyork  200000
3  linda  30     India   20000
2  peter  40  bariline   20000
1   Anna  20     paris   30000

In [22]:
df

    Name  Age        city  salary
0   john   12  california   10000
1   Anna   14          us   20000
2  Linda   16       japan   30000
3  peter   18       china   40000

# Selecting subsets of Rows and Columns

In [23]:
df.loc[[0,1]] [["city","salary"]]

         city  salary
0  california   10000
1          us   20000

In [24]:
df.loc[[2,3]] [["Name","Age"]]

    Name  Age
2  Linda   16
3  peter   18

In [25]:
# Conditional selection

In [26]:
df

    Name  Age        city  salary
0   john   12  california   10000
1   Anna   14          us   20000
2  Linda   16       japan   30000
3  peter   18       china   40000

In [27]:
df[df["Age"]<14]

   Name  Age        city  salary
0  john   12  california   10000

In [28]:
# i only want people whose salary is above 10000

In [29]:
df[df["salary"]>10000]

    Name  Age   city  salary
1   Anna   14     us   20000
2  Linda   16  japan   30000
3  peter   18  china   40000

In [30]:
# i only want people whose age is greater the  less then 20  and their city must be china

In [31]:
df[(df["Age"]>14) & (df["city"]=='china')]

    Name  Age   city  salary
3  peter   18  china   40000

In [32]:
df

    Name  Age        city  salary
0   john   12  california   10000
1   Anna   14          us   20000
2  Linda   16       japan   30000
3  peter   18       china   40000

In [33]:
df["Name"]

0     john
1     Anna
2    Linda
3    peter
Name: Name, dtype: object

In [34]:
annual_salary=df.loc[df["Name"]=="Anna","city"].iloc[0]

In [35]:
annual_salary

'us'

In [36]:
df.loc[df["Name"]=="john","salary"].iloc[0]

np.int64(10000)

In [37]:
df.loc[df["Age"]>12,"salary"].iloc[1]

np.int64(30000)

In [38]:
df

    Name  Age        city  salary
0   john   12  california   10000
1   Anna   14          us   20000
2  Linda   16       japan   30000
3  peter   18       china   40000

# Missing data

In [39]:
# How we can find the missing data

In [40]:
data = {
    "A" : [ 1,2, np.nan,4,5],
    "B" : [1,2,3,4,5],
    "c" : [1,2,3,np.nan,np.nan],
    "D" : [1,np.nan,np.nan,np.nan,5]
}
df3=pd.DataFrame(data)

In [41]:
df3

     A  B    c    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [42]:
df3.isna()

       A      B      c      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [43]:
df3.isna().sum()

A    1
B    0
c    2
D    3
dtype: int64

In [44]:
# if there is any missing value in the data

In [45]:
df3.isna().any()

A     True
B    False
c     True
D     True
dtype: bool

In [46]:
df3

     A  B    c    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [47]:
df3

     A  B    c    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [48]:
df3.dropna(thresh=1)

     A  B    c    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [49]:
# Filling the missing data

In [50]:
df3.fillna(12,inplace=True)
df3

      A  B     c     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  12.0
2  12.0  3   3.0  12.0
3   4.0  4  12.0  12.0
4   5.0  5  12.0   5.0

In [51]:
values={"A":0,"B":200,"C":300,"D":400}
df3.fillna(value=values) # column wise

      A  B     c     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  12.0
2  12.0  3   3.0  12.0
3   4.0  4  12.0  12.0
4   5.0  5  12.0   5.0

In [52]:
df3.fillna(df3.mean())

      A  B     c     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  12.0
2  12.0  3   3.0  12.0
3   4.0  4  12.0  12.0
4   5.0  5  12.0   5.0

# Merring joinign and concatination

In [53]:
#Merger two dataframe

In [54]:
salaries = pd.DataFrame({
    "employes_id":[1,2,3,6,7],
    "salary" : [6000,7000,8000,9000,60000],
    "bonus" : [5000,10000,7000,8000,12000]
})

employees=pd.DataFrame({
    'employes_id' : [1,2,3,4,5],
    "name" :  ["john","Anna","petter","linda","pooiinn"],
    "department": ["HR","IT","FINANCE","IT","HR"]
})

In [55]:
salaries

   employes_id  salary  bonus
0            1    6000   5000
1            2    7000  10000
2            3    8000   7000
3            6    9000   8000
4            7   60000  12000

In [56]:
employees

   employes_id     name department
0            1     john         HR
1            2     Anna         IT
2            3   petter    FINANCE
3            4    linda         IT
4            5  pooiinn         HR

In [57]:
df4=pd.merge(employees,salaries,on = 'employes_id',how='outer')

In [58]:
df4

   employes_id     name department   salary    bonus
0            1     john         HR   6000.0   5000.0
1            2     Anna         IT   7000.0  10000.0
2            3   petter    FINANCE   8000.0   7000.0
3            4    linda         IT      NaN      NaN
4            5  pooiinn         HR      NaN      NaN
5            6      NaN        NaN   9000.0   8000.0
6            7      NaN        NaN  60000.0  12000.0

In [59]:
df4.fillna(0,inplace=True)
df4

   employes_id     name department   salary    bonus
0            1     john         HR   6000.0   5000.0
1            2     Anna         IT   7000.0  10000.0
2            3   petter    FINANCE   8000.0   7000.0
3            4    linda         IT      0.0      0.0
4            5  pooiinn         HR      0.0      0.0
5            6        0          0   9000.0   8000.0
6            7        0          0  60000.0  12000.0

In [60]:
df4.dropna(thresh=3)

   employes_id     name department   salary    bonus
0            1     john         HR   6000.0   5000.0
1            2     Anna         IT   7000.0  10000.0
2            3   petter    FINANCE   8000.0   7000.0
3            4    linda         IT      0.0      0.0
4            5  pooiinn         HR      0.0      0.0
5            6        0          0   9000.0   8000.0
6            7        0          0  60000.0  12000.0

In [61]:
df5=df4["name"].fillna("camela"),[df4["department"].fillna("sw")]
df5

(0       john
 1       Anna
 2     petter
 3      linda
 4    pooiinn
 5          0
 6          0
 Name: name, dtype: object,
 [0         HR
  1         IT
  2    FINANCE
  3         IT
  4         HR
  5          0
  6          0
  Name: department, dtype: object])

df4["name"].fillna("meena",inplace=True)

In [62]:
#concat the two dataframes

In [63]:
 df6=pd.DataFrame({
     "A":["A0","A1","A2"],
     "B":["B0","B1","B2"],
     "C":["C1","C2","C3"]
 })                                   # LIST {}
 df7=pd.DataFrame({
     "A":["A3","A4","A5"],
     "B":["B3","B4","B5"],
     "C":["C3","C4","C5"]
 })

In [64]:
pd.concat([df6,df7],axis=1)

    A   B   C   A   B   C
0  A0  B0  C1  A3  B3  C3
1  A1  B1  C2  A4  B4  C4
2  A2  B2  C3  A5  B5  C5

# by using the join

In [71]:
df8=pd.DataFrame({
    "name":["Abhay","Akshit","charlie"]
},index = [1,2,3])
# second dataFrame 
df9=pd.DataFrame({
    "score":[85,90,75]
},index=[1,2,3])

In [72]:
df8.join(df9,how="inner")

      name  score
1    Abhay     85
2   Akshit     90
3  charlie     75

In [73]:
df8.join(df9)

      name  score
1    Abhay     85
2   Akshit     90
3  charlie     75

In [74]:
# group by aggregation

In [75]:
data={
    "category":["A","B","A","B","A","B","A","B"],
    "store":["S1","S2","S2","S1","S1","S1","S2","S1"],
    "sale":[100, 200, 150, 300, 450, 670, 210, 300],
    "quantity":[10,15,12,18,8,20,15,25],
    "Date":pd.date_range('2026-01-01',periods=8)
}
df=pd.DataFrame(data)